apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mark-repo-one-nine-one
  description: mark-repo-one-nine-one
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/workshop_users
  lifecycle: experimental
